version: "3.7"
services:
  testapp1:
    build:
      context: ./App1
      dockerfile: Dockerfile
    container_name: testapp1
    networks:
     - shared_network

  testapp2:
    build:
      context: ./App2
      dockerfile: Dockerfile
    container_name: testapp2
    networks:
    - shared_network


networks:
  shared_network:
    name: shared_network