version: "3.9"
services:
  testapp1:
    build:
      context: ./App1
      dockerfile: Dockerfile
    container_name: testapp1
    networks:
     - shared_network
    ports:
     - "8080:8080"
    volumes: 
     - "/home/bartekwysocki/Documents/Workspace/DockerQuest/files:/app/files:Z"

  testapp2:
    build:
      context: ./App2
      dockerfile: Dockerfile
    container_name: testapp2
    networks:
     - shared_network
    ports:
       - "8081:8081"
    volumes: 
     - "/home/bartekwysocki/Documents/Workspace/DockerQuest/files:/app/files:z"

networks:
  shared_network:
    name: shared_network